// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oozthrrgyvhlfaxijabl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9venRocnJneXZobGZheGlqYWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MDc5MjQsImV4cCI6MjA1Mzk4MzkyNH0.b5pxD76GwnVaSoHgoUiYK1eR7u3G2RupjTmvwuTkfLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);